/**
 * Seed 数据：由静态原型中的 mock 数据迁移而来。
 * 仅在 localStorage 对应集合为空时作为初始数据写入。
 */
import type {
  BeautyTip,
  Inspiration,
  LifeRecord,
  PeriodLog,
  PrivateDiary,
  Product,
  UsageLog,
  WeightLog,
  Wish,
} from "@/lib/types";

export const seedLifeRecords: LifeRecord[] = [
  {
    id: "seed-record-01",
    type: "diary",
    title: "我的日常妆容分享｜适合新手的温柔妆",
    content: "简单几步就能出门，适合日常通勤～",
    images: ["/images/post-1.png"],
    mood: "开心",
    weather: "晴",
    tags: ["化妆技巧", "日常", "新手"],
    visibility: "已发布",
    createdAt: "2026-08-30T10:20:00",
  },
  {
    id: "seed-record-02",
    type: "diary",
    title: "一些让生活变开心的小事",
    content: "收集日常的小确幸，把平凡的日子过得闪闪发光 ✨",
    images: ["/images/post-2.png"],
    mood: "幸福",
    weather: "多云",
    tags: ["生活", "随想", "治愈"],
    visibility: "准备分享",
    createdAt: "2026-08-28T21:05:00",
  },
  {
    id: "seed-record-03",
    type: "diary",
    title: "近期爱用好物｜回购清单",
    content: "真实自用分享，干皮友好，温和不踩雷～",
    images: ["/images/post-3.png"],
    mood: "有成就感",
    tags: ["好物推荐", "护肤", "种草"],
    visibility: "私人收藏",
    createdAt: "2026-08-26T20:40:00",
  },
  {
    id: "seed-record-04",
    type: "diary",
    title: "今天的妆容超满意",
    content: "新手奶茶妆第一次成功，出门被夸了两回，开心到路上都想跳起来～",
    images: [],
    mood: "开心",
    weather: "晴",
    tags: ["妆容"],
    visibility: "私人收藏",
    createdAt: "2026-08-30T09:30:00",
  },
  {
    id: "seed-record-05",
    type: "photo",
    title: "下班路上的晚霞",
    content: "天空是橘子汽水的颜色，忽然觉得慢一点的生活也很珍贵。",
    images: [],
    mood: "平静",
    weather: "晴",
    location: "下班路上",
    tags: ["晚霞", "摄影"],
    visibility: "私人收藏",
    createdAt: "2026-08-28T18:50:00",
  },
  {
    id: "seed-record-06",
    type: "diary",
    title: "早起打卡第一天",
    content: "七点起床做了早餐，一整天都精神满满，希望可以坚持一个月！",
    images: [],
    mood: "有成就感",
    weather: "晴",
    tags: ["早起", "打卡"],
    visibility: "仅自己",
    createdAt: "2026-08-26T08:10:00",
  },
  {
    id: "seed-record-07",
    type: "diary",
    title: "莫名低落的一天",
    content: "也不知道为什么，就是有点提不起劲。抱抱自己，早点睡吧。",
    images: [],
    mood: "难过",
    weather: "阴",
    tags: ["情绪"],
    visibility: "仅自己",
    createdAt: "2026-08-24T22:30:00",
  },
  {
    id: "seed-record-08",
    type: "diary",
    title: "和好朋友逛街啦",
    content: "试了好多条裙子，最后买了那条奶白色的，晚上吃了火锅，满足。",
    images: [],
    mood: "开心",
    weather: "晴",
    location: "万达",
    tags: ["逛街", "火锅"],
    visibility: "私人收藏",
    createdAt: "2026-08-21T19:15:00",
  },
  {
    id: "seed-record-09",
    type: "diary",
    title: "周末想去的咖啡店清单",
    content: "中山北路新开的那家日式手冲，还有老街拐角的露台位，下次天气好就去…",
    images: [],
    mood: null,
    tags: ["探店"],
    visibility: "仅自己",
    draft: true,
    createdAt: "2026-09-04T22:10:00",
  },
];

export const seedBeautyTips: BeautyTip[] = [
  {
    id: "seed-tip-01",
    category: "底妆",
    title: "温柔奶茶妆教程",
    steps: [
      "妆前保湿打底，重点照顾眼周和鼻翼",
      "薄涂粉底液，用湿海绵蛋按压上妆",
      "奶茶色眼影大面积晕染，加深眼尾",
      "豆沙色腮红斜扫在颧骨，口红选同色系",
    ],
    products: ["干皮粉底液", "奶茶色眼影盘", "豆沙色腮红"],
    notes: "新手注意少量多次，粉底别一次挤太多",
    scene: "日常通勤 / 约会",
    rating: 5,
  },
  {
    id: "seed-tip-02",
    category: "护肤",
    title: "干皮护肤回购清单",
    steps: ["温和氨基酸洁面", "保湿爽肤水湿敷 3 分钟", "精华 + 面霜锁水"],
    products: ["保湿精华", "神经酰胺面霜"],
    notes: "干皮秋冬一定要用面霜，乳液不够",
    scene: "秋冬夜间护理",
    rating: 4,
  },
  {
    id: "seed-tip-03",
    category: "底妆",
    title: "新手化妆刷选购指南",
    steps: ["先买粉底刷 + 腮红刷两把就够了", "选纤维毛，好打理不扎脸", "每月用清洗剂洗一次"],
    products: [],
    notes: "平价刷完全够用，不用一上来就买贵的",
    rating: 4,
  },
  {
    id: "seed-tip-04",
    category: "底妆",
    title: "持妆 8 小时的小技巧",
    steps: [
      "上妆前用冰镇过的化妆水收缩毛孔",
      "粉底薄涂，出油区用散粉按压定妆",
      "下午用吸油纸 + 喷雾补妆，不要直接补粉",
    ],
    products: ["定妆散粉", "保湿喷雾"],
    scene: "夏天 / 长时间外出",
    rating: 5,
  },
  {
    id: "seed-tip-05",
    category: "护肤",
    title: "平价好物合集",
    steps: [],
    products: ["保湿水乳", "防晒霜"],
    notes: "都是用空瓶的平价好物，学生党友好",
    rating: 4,
  },
  {
    id: "seed-tip-06",
    category: "唇妆",
    title: "唇釉试色收藏",
    steps: ["涂之前先润唇打底", "用指腹晕开边缘更自然"],
    products: ["奶茶色唇釉"],
    notes: "黄皮友好，素颜也能涂",
    rating: 5,
  },
];

export const seedProducts: Product[] = [
  {
    id: "seed-product-01",
    name: "奶茶色唇釉",
    brand: "Into You",
    shade: "#03",
    price: 89,
    boughtAt: "2026-06-14",
    review: "素颜涂也好看，已经用掉一半",
    favor: 5,
    repurchase: true,
  },
  {
    id: "seed-product-02",
    name: "水润粉底液",
    brand: "arfita",
    shade: "自然色",
    price: 159,
    boughtAt: "2026-04-02",
    review: "干皮友好，但夏天略粘",
    favor: 4,
    repurchase: true,
  },
  {
    id: "seed-product-03",
    name: "轻烟散粉",
    brand: "Judydoll",
    price: 45,
    boughtAt: "2026-07-20",
    review: "定妆力一般，补涂方便",
    favor: 3,
    repurchase: false,
  },
];

export const seedUsageLogs: UsageLog[] = [
  { id: "seed-usage-01", productId: "seed-product-01", date: "2026-08-30" },
  { id: "seed-usage-02", productId: "seed-product-02", date: "2026-08-30" },
  { id: "seed-usage-03", productId: "seed-product-01", date: "2026-08-27" },
  { id: "seed-usage-04", productId: "seed-product-02", date: "2026-08-26" },
  { id: "seed-usage-05", productId: "seed-product-03", date: "2026-08-24" },
];

export const seedInspirations: Inspiration[] = [
  {
    id: "seed-insp-01",
    type: "文案",
    content: "你爬山不是为了登顶，而是为了看看路上的花开了没有。",
    tags: ["文案"],
    createdAt: "2026-08-29T12:00:00",
  },
  {
    id: "seed-insp-02",
    type: "摄影",
    content: "晚霞收集者",
    tags: ["拍照"],
    createdAt: "2026-08-28T19:00:00",
  },
  {
    id: "seed-insp-03",
    type: "笔记",
    content: "猫咪踩了我一脸",
    tags: ["日常"],
    createdAt: "2026-08-27T10:00:00",
  },
  {
    id: "seed-insp-04",
    type: "文案",
    content: "慢慢来，谁还没有一段黎明前的路要走呢。",
    tags: ["文案"],
    createdAt: "2026-08-25T22:00:00",
  },
  {
    id: "seed-insp-05",
    type: "摄影",
    content: "窗边的光",
    tags: ["拍照"],
    createdAt: "2026-08-23T16:00:00",
  },
  {
    id: "seed-insp-06",
    type: "笔记",
    content: "单曲循环的日落歌单",
    tags: ["音乐", "日常"],
    createdAt: "2026-08-21T21:00:00",
  },
];

export const seedWeightLogs: WeightLog[] = [
  { id: "seed-weight-01", date: "2026-08-25", weight: 52.8 },
  { id: "seed-weight-02", date: "2026-08-28", weight: 52.5, note: "晚上称的" },
  { id: "seed-weight-03", date: "2026-08-31", weight: 52.3 },
  { id: "seed-weight-04", date: "2026-09-03", weight: 52.4, note: "吃火锅反弹了一丢丢" },
];

export const seedPeriodLogs: PeriodLog[] = [
  {
    id: "seed-period-01",
    start: "2026-07-16",
    end: "2026-07-20",
    symptoms: ["腰酸"],
    feeling: "还好",
  },
  {
    id: "seed-period-02",
    start: "2026-08-13",
    end: "2026-08-17",
    symptoms: ["疲惫", "腰酸"],
    feeling: "有点累",
    note: "记得备红糖",
  },
];

export const seedPrivateDiaries: PrivateDiary[] = [
  {
    id: "seed-pdiary-01",
    date: "2026-08-30",
    content: "今天化了新妆心情很好，想把这个状态一直保持下去。",
    mood: "开心",
  },
  {
    id: "seed-pdiary-02",
    date: "2026-08-13",
    content: "肚子有点疼，他给我泡了红糖水，突然觉得被照顾的感觉真好。",
    mood: "幸福",
  },
];

export const seedWishes: Wish[] = [
  {
    id: "seed-wish-01",
    name: "那支看中好久的口红",
    note: "攒到工资就买",
    status: "want",
    createdAt: "2026-08-20T12:00:00",
  },
];
